use_frameworks!

platform :ios, '10.0'

target 'MFSlideMenu_Example' do
  pod 'MFSlideMenu', :path => '../'

  target 'MFSlideMenu_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
